require 'plugins'
require 'colorschema'
require 'foundation'
require 'lsp'
require 'fuzzyfinder'
require 'completation'
require 'treesitter'
require 'nvim-context-vt'
require 'hop_config'
require 'autotag_config'
require 'autopairs_config'
require 'comment_config'
require 'vim-better-whitespace_config'
require 'neotree_config'
require 'autoload'
require 'keymap'

